
// Login actions
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

// Register actions
export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILED = 'REGISTER_FAILED'

// Tweets
export const TWEETS_REQUEST = 'TWEETS_REQUEST'
export const TWEETS_SUCCESS = 'TWEETS_SUCCESS'
export const TWEETS_FAILD = 'TWEETS_FAILD'

// Post a new tweet
export const POST_TWEET_REQUEST = 'POST_TWEET_REQUEST'
export const POST_TWEET_SUCCESS = 'POST_TWEET_SUCCESS'
export const POST_TWEET_FAILED = 'POST_TWEET_FAILED'
